### ISSUE TITLE
Switch to keepachangelog

### ISSUE THREAD

**Issue by glensc** [mrclay/jsmin-php#14]
https://keepachangelog.com/en/1.0.0/

**Comment by glensc** [comment]
@mrclay do you approve work done to achieve this issue?

**Comment by mrclay** [comment]
@glensc Yeah go for it!

**Comment by glensc** [comment]
Fixed with 1e5e168

@mrclay some git tags are missing:
- 2.2.0
- 2.1.6
- 2.1.4
- 2.1.2
- 2.1.0
- 1.0.1

create from possible commits or do you have them locally just not pushed out?

**Comment by glensc** [comment]
oh, nevermind, those versions were part of miniy: 012afaf
